version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:latest
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Prepare Docker Compose
          command: |
            mkdir -p /home/circleci/e2e
            cp -R * /home/circleci/e2e
      - run:
          name: Run Cypress Tests
          command: |
            cd /home/circleci/e2e
            docker-compose up --exit-code-from cypress
