version: 2.1
jobs:
  build:
    docker:
      - image: cypress/base:latest
    # working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run Cypress Tests
          command: |
            cd /e2e
            docker-compose up --exit-code-from cypress
